// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDm8lSqqmyfG_w0aGV_gDrYC8IyZ_-6SM',
    appId: '1:389819776938:android:b99655cddf62f411a275d3',
    messagingSenderId: '389819776938',
    projectId: 'picup-efa30',
    storageBucket: 'picup-efa30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAybXF8v5RJBeRGTYWEVuRX1zh0WJeg-Q4',
    appId: '1:389819776938:ios:e0c6976c4d7c0d0ba275d3',
    messagingSenderId: '389819776938',
    projectId: 'picup-efa30',
    storageBucket: 'picup-efa30.appspot.com',
    iosBundleId: 'com.example.picup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAybXF8v5RJBeRGTYWEVuRX1zh0WJeg-Q4',
    appId: '1:389819776938:ios:a765dffa433eb114a275d3',
    messagingSenderId: '389819776938',
    projectId: 'picup-efa30',
    storageBucket: 'picup-efa30.appspot.com',
    iosBundleId: 'com.example.picup.RunnerTests',
  );
}
